export const ACCOUNT_DETAILS_TEST_DATA = {
    accountHolderName: null,
    accountNumber: '28311061',
    accountSubType: null,
    accountType: 'CUR',
    balanceAvailable: '20010000',
    balanceCurrent: '20010000',
    branchCode: '1',
    classCode: '499',
    classDesc: 'Banoon Account - AED',
    createdOn: '2020-02-27',
    currencyCode: 'AED',
    customerNumber: '1443678',
    exchangeRate: 1,
    filters: { cardlessCash: false, certificateRequest: false, charityPayment: false, chequeBook: false, credit: true },
    ibanNumber: 'AE330500000000028311061',
    isDefaultAccount: false,
    isJointAccount: false,
    relationShipId: '1',
    relationShipName: 'Phoenix',
    status: 'Active',
    swiftCode: 'ABDIAEADXXX',
};
